replicaCount: 1

image:
  repository: 307836377724.dkr.ecr.ap-south-1.amazonaws.com/drupal
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}

autoscaling: {}

ingress:
  enabled: true
  host: islandora.rename.to
  tls:
    enabled: false
    resolver: http

pvc:
  ingestData:
    size: 20Gi
  islandoraData:
    size: 20Gi
  private:
    size: 20Gi
  public:
    size: 20Gi
  root:
    size: 20Gi
  
php:
  uploadMaxFilesize: 2048M
  postMaxSize: 2048M
  memoryLimit: 512M

drupal:
  dbName: drupal
  dbUser: admin
  user: drupal
  password: drupal
  siteEmail: foo@bar.com
  phpVersion: 7.4

init:
  installSite: true
  contentPacks:
    - provisioned_content
    - i8-specific

podAnnotations: {}

nodeSelector: {}

affinity: {}

tolerations: {}

podSecurityContext:
  fsGroup: 33
