replicaCount: 1

image:
  repository: 307836377724.dkr.ecr.ap-south-1.amazonaws.com/drupal
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

securityContext:
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: 
  limits:
    cpu: 1000m
    memory: 4096Mi
  requests:
    cpu: 200m
    memory: 1024Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90

ingress:
  enabled: true
  host: islandora.rename.to
  tls:
    enabled: true
    resolver: http

pvc:
  ingestData:
    size: 20Gi
  islandoraData:
    size: 20Gi
  private:
    size: 20Gi
  public:
    size: 20Gi
  root:
    size: 20Gi
  
php:
  uploadMaxFilesize: 2048M
  postMaxSize: 2048M
  memoryLimit: 512M

drupal:
  dbName: drupal
  dbUser: admin
  user: drupal
  password: drupal
  siteEmail: foo@bar.com
  phpVersion: 7.4

init:
  installSite: true
  contentPacks:
    - provisioned_content
    - i8-specific

podAnnotations: {}

nodeSelector: {}

affinity: {}

tolerations: {}

podSecurityContext: {}
