replicaCount: 1

image:
  repository: 307836377724.dkr.ecr.ap-south-1.amazonaws.com/cantaloupe
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}

autoscaling: {}

ingress:
  enabled: true
  host: islandora.rename.to
  tls:
    enabled: false
    resolver: http
