replicaCount: 1

image:
  repository: 307836377724.dkr.ecr.ap-south-1.amazonaws.com/alpaca
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}

service:
  type: ClusterIP
  port: 11213

resources: 
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 1024Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90
