replicaCount: 1

image:
  repository: 307836377724.dkr.ecr.ap-south-1.amazonaws.com/alpaca
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}

service:
  type: ClusterIP
  port: 11213

resources: {}

autoscaling: {}

