apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-db-secret
type: Opaque
stringData:
  {{- if .Values.aurora.masterUserPassword }}
  masterUserPassword: {{ .Values.aurora.masterUserPassword }}
  {{- else }}
  masterUserPassword: {{ randAlphaNum 10 | quote }}
  {{- end }}
  masterUsername: {{ .Values.aurora.masterUsername }}
