replicaCount: 1

image:
  repository: 307836377724.dkr.ecr.ap-south-1.amazonaws.com/activemq
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext:
  fsGroup: 1000
  
securityContext: {}

service:
  type: ClusterIP

resources: {}

autoscaling: {}

pvc:
  size: 20Gi

minMemory: 64M
maxMemory: 256M

podAnnotations: {}

nodeSelector: {}

affinity: {}

tolerations: {}
