apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-mq-secret
  namespace: ack-resources
type: Opaque
stringData:
  {{- if .Values.adminUserPassword }}
  adminUserPassword: {{ .Values.mq.adminUserPassword }}
  {{- else }}
  adminUserPassword: {{ randAlphaNum 15 | quote }}
  {{- end }}
  adminUsername: {{ .Values.mq.adminUsername }}
