apiVersion: v1
kind: Service
metadata:
  name: svc-crayfish
  labels:
    {{- include "crayfish.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ include "crayfish.name" .}}
  selector:
    {{- include "crayfish.selectorLabels" . | nindent 4 }}
