apiVersion: v1
kind: Service
metadata:
  name: svc-solr
  labels:
    {{- include "solr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ include "solr.name" .}}
  selector:
    {{- include "solr.selectorLabels" . | nindent 4 }}
