replicaCount: 1

image:
  repository: clamav/clamav
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}

service:
  type: ClusterIP
  port: 3310

resources: {}

autoscaling: {}

