clusterName: "tenant1"
vpc:
  vpcID: "vpc-01bd56eea5907a594" #Would prefer to get this automatically identified using AdoptedResource
aurora:
  minACU: 1
  maxACU: 2
  engine: "aurora-postgresql"
  engineVersion: "13"
  masterUsername: "adminer"
  masterUserPassword: "password" #This can be removed to let the password be randomly generated
  dbInstanceClass: "db.serverless"
