apiVersion: v1
kind: ConfigMap
metadata:
  name: drupal-env
data:
  ACTIVEMQ_STOMP_PORT: "61613"
  CLAMAV_PORT: "3310"
  DRUPAL_DB_NAME: {{ .Values.drupal.dbName }}
  DRUPAL_DB_USER: {{ .Values.drupal.dbUser }}
  DRUPAL_SITE_EMAIL: {{ .Values.drupal.siteEmail }}
  DRUPAL_USER: {{ .Values.drupal.user }}
  DRUPAL_USER_PASS: {{ .Values.drupal.password }}
  DRUPAL_TRUSTED_HOSTS: {{ template "drupal.trustedHosts" . }}
  IIIF_INGRESS_URL: {{ template "http.protocol" . }}://{{ .Values.ingress.host }}/iiif/2
  JWT_KEY_FILE: /run/secrets/crayfish/default.key
  JWT_KEY_TYPE: RS256
  MEMCACHED_PORT: "11211"
  REVERSE_PROXY: "TRUE"
  {{- if .Values.multiTenant }}
  CLAMAV_HOST: "svc-clamav.shared"
  IIIF_URL: "http://cantaloup.shared/iiif/2"
  MEMCACHED_HOST: "svc-memcached.shared"
  SOLR_HOST: "svc-solr.shared"
  {{- if not .Values.useManagedServices }}
  ACTIVEMQ_HOST: "svc-activemq.shared"
  POSTGRES_HOST: "postgres.shared"
  {{- end }}
  {{- else }}
  ACTIVEMQ_HOST: "svc-activemq"
  CLAMAV_HOST: "svc-clamav"
  IIIF_URL: "http://svc-cantaloup/cantaloupe/iiif/2"
  MEMCACHED_HOST: "svc-memcached"
  SOLR_HOST: "svc-solr"
  POSTGRES_HOST: "postgres"
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: drupal-php-ini
data:
    99-config.ini: |
      memory_limit = {{ .Values.php.uploadMaxFilesize }}
      post_max_size = {{ .Values.php.postMaxSize }}
      upload_max_filesize = {{ .Values.php.memoryLimit }}
