apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drupal.fullname" . }}
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "drupal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "drupal.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "drupal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-{{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            - '/bin/bash'
            - '-c'
            - |
                sleep 3600 \
                drush site-install \
                    dgi_standard_profile \
                    --db-url=pgsql://$DRUPAL_DB_USER:$DRUPAL_DB_PASSWORD@$POSTGRES_HOST:5432/$DRUPAL_DB_NAME \
                    --site-name=default_site \
                    --account-name=$DRUPAL_USER \
                    --account-pass=$DRUPAL_USER_PASS \
                    --account-mail=$DRUPAL_SITE_EMAIL \
                    --sites-subdir=default \
                    --existing-config \
                    -y
                {{- range $contentPack := .Values.init.contentPacks }}
                drush content-sync:import {{ $contentPack }} --actions=create --user=1 -y
                {{- end }}
                drush -y migrate:import --userid=1 --group=islandora
                drush -y state-set dgi_i8_helper_iiif_site_id drupal_d8_default
          envFrom:
          - configMapRef:
              name: drupal-env
          env:
          - name: DRUPAL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password              
          volumeMounts:
          - name: crayfish-key
            mountPath: /run/secrets/crayfish
          - name: public
            mountPath: /opt/www/drupal/web/sites/default/files
          - name: private
            mountPath: /opt/drupal_private_filesystem/d8/default
          - name: islandora-data
            mountPath: /opt/islandora_data
          - name: ingest-data
            mountPath: /opt/ingest_data
          - name: drupal-php-ini
            mountPath: /etc/php/{{ .Values.drupal.phpVersion }}/apache2/conf.d/99-config.ini
            subPath: 99-config.ini
          - name: drupal-php-ini
            mountPath: /etc/php/{{ .Values.drupal.phpVersion }}/cli/conf.d/99-config.ini
            subPath: 99-config.ini
          - name: root
            mountPath: /opt/www/drupal
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: drupal-env
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: crayfish-key
            mountPath: /run/secrets/crayfish
          - name: public
            mountPath: /opt/www/drupal/web/sites/default/files
          - name: private
            mountPath: /opt/drupal_private_filesystem/d8/default
          - name: islandora-data
            mountPath: /opt/islandora_data
          - name: ingest-data
            mountPath: /opt/ingest_data
          - name: drupal-php-ini
            mountPath: /etc/php/{{ .Values.drupal.phpVersion }}/apache2/conf.d/99-config.ini
            subPath: 99-config.ini
          - name: drupal-php-ini
            mountPath: /etc/php/{{ .Values.drupal.phpVersion }}/cli/conf.d/99-config.ini
            subPath: 99-config.ini
          - name: root
            mountPath: /opt/www/drupal
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: drupal-php-ini
        configMap:
          name: drupal-php-ini
      - name: crayfish-key
        secret:
          secretName: crayfish-key
          items:
          - key: ssh-privatekey
            path: default.key
      - name: public
        persistentVolumeClaim:
          claimName: drupal-public-claim
      - name: private
        persistentVolumeClaim:
          claimName: drupal-private-claim
      - name: islandora-data
        persistentVolumeClaim:
          claimName: drupal-islandora-data-claim
      - name: ingest-data
        persistentVolumeClaim:
          claimName: drupal-ingest-data-claim
      - name: root
        persistentVolumeClaim:
          claimName: drupal-root-claim
