apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-ingest-data-claim
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
spec:
  {{- if .Values.rwxStorageClass }}
  storageClassName: {{ .Values.rwxStorageClass }}
  accessModes:
    - ReadWriteMany
  {{- else }}
  accessModes:
    - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.ingestData.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-islandora-data-claim
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
spec:
  {{- if .Values.rwxStorageClass }}
  storageClassName: {{ .Values.rwxStorageClass }}
  accessModes:
    - ReadWriteMany
  {{- else }}
  accessModes:
    - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.islandoraData.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-private-claim
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
spec:
  {{- if .Values.rwxStorageClass }}
  storageClassName: {{ .Values.rwxStorageClass }}
  accessModes:
    - ReadWriteMany
  {{- else }}
  accessModes:
    - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.private.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-public-claim
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
spec:
  {{- if .Values.rwxStorageClass }}
  storageClassName: {{ .Values.rwxStorageClass }}
  accessModes:
    - ReadWriteMany
  {{- else }}
  accessModes:
    - ReadWriteOnce
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.public.size }}
