replicaCount: 1

image:
  repository: 307836377724.dkr.ecr.ap-south-1.amazonaws.com/solr
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext:
  fsGroup: 1000

service:
  type: ClusterIP
  port: 8983

resources: {}

autoscaling: {}

rwostorageclass: gp2
pvc:
  size: 20Gi
