apiVersion: v1
kind: Service
metadata:
  name: svc-activemq
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
spec:
  ports:
    - name: admin
      port: 8161
      protocol: TCP
      targetPort: admin
    - name: stomp
      port: 61613
      protocol: TCP
      targetPort: stomp
    - name: tcp
      port: 61616
      protocol: TCP
      targetPort: tcp
  type: {{ .Values.service.type }}
  selector:
    {{- include "activemq.selectorLabels" . | nindent 4 }}
